def get_language_dict(lang):
    """Get language dictionary based on selected language"""
    language_dict = {
        "తెలుగు": {
            "title": "📚 WordTalk – తెలుగు స్లాంగ్ కోషం",
            "subtitle": "మీ స్లాంగ్ పదాలను పంచుకోండి మరియు తెలుగు భాష కోశాన్ని సమృద్ధి చేయండి",
            "login_title": "🔐 లాగిన్ పేజీ",
            "login_subtitle": "కొనసాగించడానికి దయచేసి మీ వివరాలను పూరించండి",
            "main_app": "📚 ప్రధాన యాప్",
            "word_explanation": "🧠 పదాల వివరణ",
            "leaderboard": "🏆 లీడర్‌బోర్డ్",
            "logout": "🚪 లాగౌట్",
            "nickname": "మీ పేరు/Nickname *",
            "geo": "మీ ప్రాంతం *",
            "name": "పూర్తి పేరు *",
            "age": "వయస్సు *",
            "gender": "లింగం *",
            "education": "విద్యార్హత *",
            "occupation": "వృత్తి *",
            "coordinates": "కోఆర్డినేట్స్ (అవసరం) *",
            "latitude": "అక్షాంశం *",
            "longitude": "రేఖాంశం *",
            "get_location": "🌍 నా స్థానం పొందండి",
            "login_btn": "లాగిన్ చేయండి",
            "validation_error": "దయచేసి అన్ని అవసరమైన ఫీల్డ్‌లను (*) పూరించండి",
            "location_success": "✅ స్థానం విజయవంతంగా పొందబడింది",
            "login_success": "✅ విజయవంతంగా లాగిన్ అయ్యారు!",
            "category": "కోర్పస్ వర్గం *",
            "corpus_title": "శీర్షిక *",
            "corpus_desc": "వివరణ (స్లాంగ్ వివరణ) *",
            "words_label": "ఈ పదాలను మీ స్వంత మాటల్లో వివరించండి",
            "submit": "సబ్మిట్ చేయి",
            "new_words": "🔄 కొత్త పదాలు",
            "your_score": "మీ మొత్తం స్కోర్",
            "top_contributors": "🏆 టాప్ కంట్రిబ్యూటర్లు",
            "continue_to_words": "📝 పదాల వివరణకు కొనసాగండి",
            "words_to_explain": "వివరించవలసిన పదాలు",
            "back_to_corpus": "⬅️ కోర్పస్ వివరాలకు తిరిగి వెళ్లండి"
        },
        "English": {
            "title": "📚 WordTalk – Telugu Slang Collector",
            "subtitle": "Share your slang words and enrich the Telugu language corpus",
            "login_title": "🔐 Login Page",
            "login_subtitle": "Please fill in your details to continue",
            "main_app": "📚 Main App",
            "word_explanation": "🧠 Word Explanation",
            "leaderboard": "🏆 Leaderboard",
            "logout": "🚪 Logout",
            "nickname": "Your Name/Nickname *",
            "geo": "Your Area *",
            "name": "Full Name *",
            "age": "Age *",
            "gender": "Gender *",
            "education": "Education *",
            "occupation": "Occupation *",
            "coordinates": "Coordinates (Required) *",
            "latitude": "Latitude *",
            "longitude": "Longitude *",
            "get_location": "🌍 Get My Location",
            "login_btn": "Login",
            "validation_error": "Please fill all required fields (*)",
            "location_success": "✅ Location obtained successfully",
            "login_success": "✅ Login successful!",
            "category": "Corpus Category *",
            "corpus_title": "Title *",
            "corpus_desc": "Description (Slang meaning) *",
            "words_label": "Explain these words in your own slang",
            "submit": "Submit",
            "new_words": "🔄 New Words",
            "your_score": "Your Total Score",
            "top_contributors": "🏆 Top Contributors",
            "continue_to_words": "📝 Continue to Word Explanation",
            "words_to_explain": "Words to Explain",
            "back_to_corpus": "⬅️ Back to Corpus Details"
        }
    }
    
    return language_dict.get(lang, language_dict["English"])